
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "Name": "Danilo Yukio Kodavara",
    "Email": "danilo@email.com"
}

> {% client.global.set("clientId", response.body.id); %}
###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "{{clientId}}"
}

> {% client.global.set("accountId", response.body.id); %}
###

POST http://localhost:8080/deposits HTTP/1.1
Content-Type: application/json

{
    "account_id": "{{accountId}}",
    "amount": 100
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "f8df753c-3b58-43aa-8016-12aaa4f1ea3e",
    "account_id_to": "0216ea38-524f-4e85-8743-d484a8f7538e",
    "amount": 1
}

